language: java
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: sZxVXyuzwvYnh1tLbZbLr0EcUVka7k+O4jJkZRgEfhVvwZ2FEtldN2l800F3fveP91DW1oPZfRv9FRBOLE5muIyJYHy3bMMCdnAr0F3oB5BNaA9RAujFkvPiKTkdP+UwREfPnAHZsKXBUbaTl4BZoJtrA6eJY7eslHMFIYGdYkOGrpuOCMVAvKY7BhtoYdOeli/jImfeIYOxqf6m713BWjIfQ3IBOCscNHScpG0eSKP2u5rnWxNnBo4g+45b7Zu1RR5sLQEVLtGoSMydt55a6LbTXFwOc+RyIrYmOrTBft7G9VSUnLqdvmevIjNqQ9FnNMX/QIoV6osdHqWTV7HSlRExDGc8HYRCgeKy5UJX/OCy3m/+nxnoj7NBdqF9zn38GZTO4aHlZholFrpfiVYILongw0SASslV5oC5xleZ/yL2WLvrmgnTBgKd1vLkqQvfxDL5yoOCjfKcpBNnCol2SP1FQEmVW8liS00FxhBGCfN04iX3BVT3XK9abDJfwSAJ1OYwKCojkTAgs/gbqkvsZvWOy+yOzswyZDhnaDYG6wuhCgsesV3G7LAKGT17tyOBNX/GTe6dAoeOLcGbgGL065+Ow1OsvGGoQixDmcRdvfFxy5w7kPjXATADkkm3M5mgUUH2zYzJc350uPhibgA7H8WtzR2AoZYnArDs1AFe9Bw=
